// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Tracker.Data;

#nullable disable

namespace TrackerApi.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260619120000_AddReleaseTracking")]
    partial class AddReleaseTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
